#!/usr/bin/env python3
"""
Regenerate custom_presets.h from a GBS-Control backup .bin dump.

Usage:
    python3 scripts/update_custom_presets.py <path-to-backup.bin>

The backup format is the one produced by the WebUI "Backup" feature:
    [4 bytes BE uint32 = JSON size]
    [JSON: {"/path": size, ...}]
    [concatenated file contents]

Generated output: custom_presets.h at the repository root, with:
  - One PROGMEM uint8_t array per preset file
  - gbsc_custom_preset_map[]: maps each array to its SPIFFS path
  - gbsc_custom_slots[]: 5 named slot definitions parsed from slots.bin
"""

import json
import os
import re
import struct
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_HEADER = REPO_ROOT / "custom_presets.h"


def parse_backup(bin_path: Path):
    data = bin_path.read_bytes()
    json_size = struct.unpack(">I", data[:4])[0]
    header = json.loads(data[4:4 + json_size])
    files = {}
    offset = 4 + json_size
    for path, size in header.items():
        files[path] = data[offset:offset + size]
        offset += size
    if offset != len(data):
        print(f"  warning: {len(data) - offset} trailing bytes ignored", file=sys.stderr)
    return files


def parse_preset_text(blob: bytes) -> list[int]:
    """Each preset file is a CSV of decimal byte values, terminated by '};'."""
    nums = re.findall(rb"\d+", blob)
    return [int(n) for n in nums]


def parse_slots(blob: bytes):
    """slots.bin: 72 entries × 32 bytes each.
    Layout per slot: name[25], presetID, scanlines, scanlinesStrength,
                     slot, wantVdsLineFilter, wantStepResponse, wantPeaking
    """
    slots = []
    for i in range(72):
        off = i * 32
        name = blob[off:off + 25].decode("latin-1").strip("\x00 ").rstrip()
        slots.append({
            "idx": i,
            "name": name,
            "presetID": blob[off + 25],
            "scanlines": blob[off + 26],
            "scanlinesStrength": blob[off + 27],
            "slot": blob[off + 28],
            "wantVdsLineFilter": blob[off + 29],
            "wantStepResponse": blob[off + 30],
            "wantPeaking": blob[off + 31],
        })
    return slots


def c_identifier(filename: str) -> str:
    """/preset_ntsc.A -> gbsc_custom_preset_ntsc_A"""
    base = filename.lstrip("/").replace(".", "_")
    return "gbsc_custom_" + base


def render_header(preset_files: list[tuple[str, list[int]]], named_slots: list[dict]) -> str:
    lines = [
        "#ifndef _CUSTOM_PRESETS_H_",
        "#define _CUSTOM_PRESETS_H_",
        "",
        "// Auto-generated by scripts/update_custom_presets.py",
        "// Do not edit by hand. Regenerate from a fresh backup dump.",
        "",
        "#include <Arduino.h>",
        "",
    ]

    for path, values in preset_files:
        cname = c_identifier(path)
        lines.append(f"// {path} ({len(values)} bytes)")
        lines.append(f"const uint8_t {cname}[] PROGMEM = {{")
        for i in range(0, len(values), 16):
            chunk = ", ".join(f"{v:>3}" for v in values[i:i + 16])
            lines.append(f"  {chunk},")
        lines.append("};")
        lines.append("")

    lines.append("struct GbscCustomPresetEntry {")
    lines.append("  const char* path;")
    lines.append("  const uint8_t* data;")
    lines.append("  uint16_t length;")
    lines.append("};")
    lines.append("")
    lines.append("const GbscCustomPresetEntry gbsc_custom_preset_map[] = {")
    for path, values in preset_files:
        cname = c_identifier(path)
        lines.append(f'  {{ "{path}", {cname}, {len(values)} }},')
    lines.append("};")
    lines.append(f"const uint8_t gbsc_custom_preset_map_size = {len(preset_files)};")
    lines.append("")

    lines.append("struct GbscCustomSlotDef {")
    lines.append("  uint8_t slotIdx;")
    lines.append("  const char* name;")
    lines.append("  uint8_t scanlines;")
    lines.append("  uint8_t scanlinesStrength;")
    lines.append("  uint8_t wantVdsLineFilter;")
    lines.append("  uint8_t wantStepResponse;")
    lines.append("  uint8_t wantPeaking;")
    lines.append("};")
    lines.append("")
    lines.append("const GbscCustomSlotDef gbsc_custom_slots[] = {")
    for s in named_slots:
        padded_name = s["name"].ljust(24)[:24]
        lines.append(
            f'  {{ {s["idx"]:>2}, "{padded_name}", '
            f'{s["scanlines"]}, {s["scanlinesStrength"]}, '
            f'{s["wantVdsLineFilter"]}, {s["wantStepResponse"]}, {s["wantPeaking"]} }},'
        )
    lines.append("};")
    lines.append(f"const uint8_t gbsc_custom_slots_size = {len(named_slots)};")
    lines.append("")
    lines.append("#endif")
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <path-to-backup.bin>", file=sys.stderr)
        sys.exit(1)

    bin_path = Path(sys.argv[1]).expanduser()
    if not bin_path.is_file():
        print(f"error: file not found: {bin_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Reading {bin_path}")
    files = parse_backup(bin_path)

    preset_files = []
    slots_blob = None
    for path, blob in files.items():
        if path == "/slots.bin":
            slots_blob = blob
        elif path.startswith("/preset_"):
            preset_files.append((path, parse_preset_text(blob)))

    if not preset_files:
        print("error: no preset_* files found in backup", file=sys.stderr)
        sys.exit(2)
    if slots_blob is None:
        print("error: slots.bin missing from backup", file=sys.stderr)
        sys.exit(2)

    preset_files.sort(key=lambda x: x[0])

    slots = parse_slots(slots_blob)
    named_slots = [s for s in slots if s["name"] and s["name"] != "Empty"]

    print(f"  {len(preset_files)} preset file(s), {len(named_slots)} named slot(s)")
    for s in named_slots:
        print(f"    slot {s['idx']:>2} ({chr(ord('A') + s['idx'])}): {s['name']}")
    for path, values in preset_files:
        print(f"    {path}: {len(values)} registers")

    header = render_header(preset_files, named_slots)
    OUT_HEADER.write_text(header)
    print(f"Wrote {OUT_HEADER} ({OUT_HEADER.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
